# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name: "Frauen Lese kreise"
description: "Ein Buchclub fur Frauen die Deutsch als Fremdsprache lernen"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "http://blog.zehrah.net"
author:             "Zehra Hayirci"
#twitter:
#  username:         "zehayirci"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "/frauenlesekreise"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    remote:         false
    localpath:      "/about"
  - name:           "Archive"
    remote:         false
    localpath:      "archive"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
