# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name: "Frauen Lese kreise"
description: "Ein Buchclub fur Frauen die Deutsch als Fremdsprache lernen"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "http://blog.zehrah.net"
author:             "Zehra Hayirci"
#twitter:
#  username:         "zehayirci"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "/frauenlesekreise"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown


# Navigation
nav:
  - name: "About"
    href: "/frauenlesekreise/about"
  - name: "Archive"
    href: "/frauenlesekreise/archive"

# Sass
sass:
  style:            :compressed

#collection
collections:
  archives:
    output: true
    permalink: /archives/:path/

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         "{{ site.baseurl }}/archive"
      type:         "archive"
    values:         "archive"
      layout:       "archive"

gems:
  - jekyll-seo-tag
